node('slave') {  
    stage('Build') { 
        sh 'make --directory=ttmm all'
    }
    stage('Test') { 
        sh './tests/test0.sh'
        sh './tests/test1.sh'
        sh './tests/test2.sh'
    }
    stage('Cleanup') {
        sh 'make --directory=ttmm clean'
    }
}
